name: CI_for_NotesApplication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run a multi-line script
      run: |
      
        cmake .
        make
        ./bin/runTests
