name: CI_for_NotesApplication

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run all Tests
      run: |
      
        cmake .
        make
        ./bin/runAllTests

    - name: Run Valgrind
      run: |

        g++ -g -O0 src/folder.cpp src/folderManager.cpp src/main.cpp src/note.cpp src/runMenus.cpp -o runProgValgrind
        valgrind --tool=memcheck --leak-check=yes ./runProgValgrind
        
